/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    _collection: typeof import('./../components/_collection/index.vue')['default']
    BachelorDegree: typeof import('./../components/icons/BachelorDegree.vue')['default']
    ButtonWithSvg: typeof import('./../components/basic-material/ButtonWithSvg.vue')['default']
    CollectionItem: typeof import('./../components/_collection/CollectionItem.vue')['default']
    Dialog: typeof import('./../components/more-layer/dialog/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FanTable: typeof import('./../components/module/FanTable.vue')['default']
    HandsonTable: typeof import('./../components/module/HandsonTable.vue')['default']
    HelpTooltip: typeof import('./../components/more-layer/tooltip/HelpTooltip.vue')['default']
    IconBaseline: typeof import('./../components/icons/IconBaseline.vue')['default']
    IconClose: typeof import('./../components/icons/IconClose.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconOutline: typeof import('./../components/icons/IconOutline.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    Menu: typeof import('./../components/navigation/menu/index.vue')['default']
    MonacoEditor: typeof import('./../components/module/MonacoEditor.vue')['default']
    MyDialog: typeof import('./../components/more-layer/dialog/MyDialog.vue')['default']
    QuarterSector: typeof import('./../components/icons/QuarterSector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
