<template>
  <div>
    <FanTable :columns="columns" :tableData="tableData" :max-height="500"></FanTable>
  </div>
</template>

<script lang="ts" setup>
import 'vue-fantable/libs/theme-default.css'
const columns = ref([
          { field: 'name', key: 'a', title: 'Name', align: 'center' },
          { field: 'date', key: 'b', title: 'Date', align: 'left' },
          { field: 'hobby', key: 'c', title: 'Hobby', align: 'right' },
          { field: 'address', key: 'd', title: 'Address' },
        ])
const tableData = ref([
          {
            name: 'John',
            date: '1900-05-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shanghai',
          },
          {
            name: 'Dickerson',
            date: '1910-06-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Beijing',
          },
          {
            name: 'Larsen',
            date: '2000-07-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Chongqing',
          },
          {
            name: 'Geneva',
            date: '2010-08-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Xiamen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
          {
            name: 'Jami',
            date: '2020-09-20',
            hobby: 'coding and coding repeat',
            address: 'No.1 Century Avenue, Shenzhen',
          },
        ])
</script>

<style lang="scss" scoped>

</style>
